name: skinsight-env
channels:
  - defaults
dependencies:
  - tensorflow
  - numpy
  - pillow
  - ipykernel
  - notebook
  - matplotlib
  - pandas
  - seaborn
  - scikit-learn
  - fastapi
  - uvicorn
  - python-multipart
  - pip